multi_dof_joints:
  - name: world_joint
    type: Floating
    parent_frame_id: base_footprint
    child_frame_id: base_footprint
groups:
  - name: arm
    base_link: base_link
    tip_link: arm_link_5
default_collision_operations:
  - object1: base_footprint
    object2: base_link
    operation: disable  # Adjacent in collision
  - object1: base_link
    object2: arm_link_0
    operation: disable  # Adjacent in collision
  - object1: arm_link_0
    object2: arm_link_1
    operation: disable  # Adjacent in collision
  - object1: arm_link_1
    object2: arm_link_2
    operation: disable  # Adjacent in collision
  - object1: arm_link_2
    object2: arm_link_3
    operation: disable  # Adjacent in collision
  - object1: arm_link_3
    object2: arm_link_4
    operation: disable  # Adjacent in collision
  - object1: arm_link_4
    object2: arm_link_5
    operation: disable  # Adjacent in collision
  - object1: arm_link_5
    object2: gripper_palm_link
    operation: disable  # Adjacent in collision
  - object1: gripper_palm_link
    object2: gripper_finger_link_l
    operation: disable  # Adjacent in collision
  - object1: gripper_palm_link
    object2: gripper_finger_link_r
    operation: disable  # Adjacent in collision
  - object1: base_link
    object2: base_laser_front_link
    operation: disable  # Adjacent in collision
  - object1: base_link
    object2: caster_link_bl
    operation: disable  # Adjacent in collision
  - object1: caster_link_bl
    object2: wheel_link_bl
    operation: disable  # Adjacent in collision
  - object1: base_link
    object2: caster_link_br
    operation: disable  # Adjacent in collision
  - object1: caster_link_br
    object2: wheel_link_br
    operation: disable  # Adjacent in collision
  - object1: base_link
    object2: caster_link_fl
    operation: disable  # Adjacent in collision
  - object1: caster_link_fl
    object2: wheel_link_fl
    operation: disable  # Adjacent in collision
  - object1: base_link
    object2: caster_link_fr
    operation: disable  # Adjacent in collision
  - object1: caster_link_fr
    object2: wheel_link_fr
    operation: disable  # Adjacent in collision
  - object1: base_link
    object2: plate_link
    operation: disable  # Adjacent in collision
  - object1: base_link
    object2: wheel_link_br
    operation: disable  # Default in collision
  - object1: base_link
    object2: wheel_link_bl
    operation: disable  # Default in collision
  - object1: base_link
    object2: wheel_link_fl
    operation: disable  # Default in collision
  - object1: base_link
    object2: wheel_link_fr
    operation: disable  # Default in collision
  - object1: arm_link_0
    object2: arm_link_2
    operation: disable  # Never in collision
  - object1: arm_link_0
    object2: base_footprint
    operation: disable  # Never in collision
  - object1: arm_link_0
    object2: base_laser_front_link
    operation: disable  # Never in collision
  - object1: arm_link_0
    object2: plate_link
    operation: disable  # Never in collision
  - object1: arm_link_0
    object2: wheel_link_bl
    operation: disable  # Never in collision
  - object1: arm_link_0
    object2: wheel_link_br
    operation: disable  # Never in collision
  - object1: arm_link_0
    object2: wheel_link_fl
    operation: disable  # Never in collision
  - object1: arm_link_0
    object2: wheel_link_fr
    operation: disable  # Never in collision
  - object1: arm_link_1
    object2: base_footprint
    operation: disable  # Never in collision
  - object1: arm_link_1
    object2: base_laser_front_link
    operation: disable  # Never in collision
  - object1: arm_link_1
    object2: base_link
    operation: disable  # Never in collision
  - object1: arm_link_1
    object2: plate_link
    operation: disable  # Never in collision
  - object1: arm_link_1
    object2: wheel_link_bl
    operation: disable  # Never in collision
  - object1: arm_link_1
    object2: wheel_link_br
    operation: disable  # Never in collision
  - object1: arm_link_1
    object2: wheel_link_fl
    operation: disable  # Never in collision
  - object1: arm_link_1
    object2: wheel_link_fr
    operation: disable  # Never in collision
  - object1: arm_link_2
    object2: base_footprint
    operation: disable  # Never in collision
  - object1: arm_link_2
    object2: base_laser_front_link
    operation: disable  # Never in collision
  - object1: arm_link_2
    object2: base_link
    operation: disable  # Never in collision
  - object1: arm_link_2
    object2: plate_link
    operation: disable  # Never in collision
  - object1: arm_link_2
    object2: wheel_link_bl
    operation: disable  # Never in collision
  - object1: arm_link_2
    object2: wheel_link_br
    operation: disable  # Never in collision
  - object1: arm_link_2
    object2: wheel_link_fl
    operation: disable  # Never in collision
  - object1: arm_link_2
    object2: wheel_link_fr
    operation: disable  # Never in collision
  - object1: arm_link_3
    object2: arm_link_5
    operation: disable  # Never in collision
  - object1: arm_link_3
    object2: base_footprint
    operation: disable  # Never in collision
  - object1: arm_link_3
    object2: base_laser_front_link
    operation: disable  # Never in collision
  - object1: arm_link_3
    object2: gripper_finger_link_l
    operation: disable  # Never in collision
  - object1: arm_link_3
    object2: gripper_finger_link_r
    operation: disable  # Never in collision
  - object1: arm_link_3
    object2: gripper_palm_link
    operation: disable  # Never in collision
  - object1: arm_link_3
    object2: wheel_link_bl
    operation: disable  # Never in collision
  - object1: arm_link_3
    object2: wheel_link_br
    operation: disable  # Never in collision
  - object1: arm_link_4
    object2: base_footprint
    operation: disable  # Never in collision
  - object1: arm_link_4
    object2: gripper_finger_link_l
    operation: disable  # Never in collision
  - object1: arm_link_4
    object2: gripper_finger_link_r
    operation: disable  # Never in collision
  - object1: arm_link_4
    object2: gripper_palm_link
    operation: disable  # Never in collision
  - object1: arm_link_4
    object2: wheel_link_bl
    operation: disable  # Never in collision
  - object1: arm_link_4
    object2: wheel_link_br
    operation: disable  # Never in collision
  - object1: arm_link_5
    object2: base_footprint
    operation: disable  # Never in collision
  - object1: arm_link_5
    object2: gripper_finger_link_l
    operation: disable  # Never in collision
  - object1: arm_link_5
    object2: gripper_finger_link_r
    operation: disable  # Never in collision
  - object1: arm_link_5
    object2: wheel_link_bl
    operation: disable  # Never in collision
  - object1: arm_link_5
    object2: wheel_link_br
    operation: disable  # Never in collision
  - object1: base_footprint
    object2: base_laser_front_link
    operation: disable  # Never in collision
  - object1: base_footprint
    object2: gripper_finger_link_l
    operation: disable  # Never in collision
  - object1: base_footprint
    object2: gripper_finger_link_r
    operation: disable  # Never in collision
  - object1: base_footprint
    object2: gripper_palm_link
    operation: disable  # Never in collision
  - object1: base_footprint
    object2: plate_link
    operation: disable  # Never in collision
  - object1: base_footprint
    object2: wheel_link_bl
    operation: disable  # Never in collision
  - object1: base_footprint
    object2: wheel_link_br
    operation: disable  # Never in collision
  - object1: base_footprint
    object2: wheel_link_fl
    operation: disable  # Never in collision
  - object1: base_footprint
    object2: wheel_link_fr
    operation: disable  # Never in collision
  - object1: base_laser_front_link
    object2: plate_link
    operation: disable  # Never in collision
  - object1: base_laser_front_link
    object2: wheel_link_bl
    operation: disable  # Never in collision
  - object1: base_laser_front_link
    object2: wheel_link_br
    operation: disable  # Never in collision
  - object1: base_laser_front_link
    object2: wheel_link_fl
    operation: disable  # Never in collision
  - object1: base_laser_front_link
    object2: wheel_link_fr
    operation: disable  # Never in collision
  - object1: gripper_finger_link_l
    object2: gripper_finger_link_r
    operation: disable  # Never in collision
  - object1: plate_link
    object2: wheel_link_bl
    operation: disable  # Never in collision
  - object1: plate_link
    object2: wheel_link_br
    operation: disable  # Never in collision
  - object1: plate_link
    object2: wheel_link_fl
    operation: disable  # Never in collision
  - object1: plate_link
    object2: wheel_link_fr
    operation: disable  # Never in collision
  - object1: wheel_link_bl
    object2: wheel_link_br
    operation: disable  # Never in collision
  - object1: wheel_link_bl
    object2: wheel_link_fl
    operation: disable  # Never in collision
  - object1: wheel_link_bl
    object2: wheel_link_fr
    operation: disable  # Never in collision
  - object1: wheel_link_br
    object2: wheel_link_fl
    operation: disable  # Never in collision
  - object1: wheel_link_br
    object2: wheel_link_fr
    operation: disable  # Never in collision
  - object1: wheel_link_fl
    object2: wheel_link_fr
    operation: disable  # Never in collision